version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    # Optional: Add volume mounts if needed
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf